version: "3.8"

services:
  pocketbase:
    image: elestio/pocketbase
    container_name: pocketbase
    environment:
      PB_ENCRYPTION_SECRET: ${PB_ENCRYPTION_SECRET}
    volumes:
      - ./pb_data:/pb_data
    ports:
      - "8090:8090"
